---
- name: create users from csv file
  hosts: localhost
  tasks:
  - name: reading the csv file
    read_csv:
      path: usuarios-novo.csv
    register: user_list
    delegate_to: localhost

  - name: display user_list data
    debug:
      var: user_list.list

  - name: Create users IAM on AWS
    command: > 
      aws iam create-user --user-name  {{ item.usuarios }}
    loop: "{{ user_list.list }}"

  - name: Create Group for user
    command: > 
      aws iam add-user-to-group --user-name {{ item.usuarios }} --group-name {{ item.grupo }}
    loop: "{{ user_list.list }}"

  - name: Create password for user
    command: > 
      aws iam create-login-profile --password-reset-required --user-name {{ item.usuarios }} --password {{ item.senha }}
    loop: "{{ user_list.list }}"